### ISSUE TITLE
-

### ISSUE THREAD

**Issue by xxd137494375** [oldratlee/translations#126]
在看2.14.2版本的源码中，发现registerThreadLocal函数在处理threadLocalHolder并发修改问题时，即加了锁，又使用了copy on write思想。对于这里有个疑问，加了锁，已经保证了线程安全，为何还要使用copy on write？ 是在考虑什么隐藏问题吗？

 public static <T> boolean registerThreadLocal(@NonNull ThreadLocal<T> threadLocal, @NonNull TtlCopier<T> copier, boolean force) {
            if (threadLocal instanceof TransmittableThreadLocal) {
                logger.warning("register a TransmittableThreadLocal instance, this is unnecessary!");
                return true;
            }

            synchronized (threadLocalHolderUpdateLock) {
                if (!force && threadLocalHolder.containsKey(threadLocal)) return false;

                WeakHashMap<ThreadLocal<Object>, TtlCopier<Object>> newHolder = new WeakHashMap<>(threadLocalHolder);
                newHolder.put((ThreadLocal<Object>) threadLocal, (TtlCopier<Object>) copier);
                threadLocalHolder = newHolder;
                return true;
            }
        }

**Comment by oldratlee** [comment]
@xxd137494375 好问题～ `TTL`的 issue 请重新提到 💕
https://github.com/alibaba/transmittable-thread-local/issues

PS: 问一下，为什么你会提这个库里来？

**Comment by xxd137494375** [comment]
https://github.com/sanbit/transmittable-thread-local/blob/master/README-EN.md 从这个链接里点进来的。。。

**Comment by oldratlee** [comment]
> https://github.com/sanbit/transmittable-thread-local/blob/master/README-EN.md 从这个链接里点进来的。。。

好的。

我再确认了一下目前应该没有了，之前有链接错误的。


-----

到 https://github.com/alibaba/transmittable-thread-local/issues
再提一下吧
