### ISSUE TITLE
git集中式工作流

### ISSUE THREAD

**Issue by Zibeon** [oldratlee/translations#19]
原文有这么一段话:
```
git pull --rebase

# 【译注】：
# 原文用的命令是 git push --rebase origin master
# 原因同上
```

其中 git **push** --rebase origin master 应为
git **pull** --rebase origin master

[原文地址](https://github.com/oldratlee/translations/blob/master/git-workflows-and-tutorials/workflow-centralized.md)

**Comment by oldratlee** [comment]
多谢指正 :+1: 

另外，方便给个Pull Request不？ :smile_cat:   
\# 要不麻烦我自己来，哈哈

**Comment by Zibeon** [comment]
已发送Pull Request. 这么晚了还没休息啊.太拼了吧.我这边才下午,还没下班呢.嘻嘻

**Comment by oldratlee** [comment]
多谢！

PS:
哈哈，还好。 我在杭州，下午， :smiley_cat:
