### ISSUE TITLE
你好，问一个hotfix分支的问题

### ISSUE THREAD

**Issue by ThomasLau** [oldratlee/translations#2]
文中提到的，`hotfix`分支使用方式是不是点问题。因为从图上看，这个似乎是不能像`release`分支一样，去走一个发布流程，这不符合规范吧。

**Comment by oldratlee** [comment]
你说的是  [`Gitflow`工作流 - 维护分支](https://github.com/oldratlee/translations/blob/master/git-workflows-and-tutorials/workflow-gitflow.md#%E7%BB%B4%E6%8A%A4%E5%88%86%E6%94%AF)中的：

> 维护分支
>
> ![](images/git-workflow-release-cycle-4maintenance.png)
>
> 维护分支或说是热修复（`hotfix`）分支用于生成快速给产品发布版本（`production releases`）打补丁，这是唯一可以直接从`master`分支`fork`出来的分支。
修复完成，修改应该马上合并回`master`分支和`develop`分支（当前的发布分支），`master`分支应该用新的版本号打好`Tag`。
>
> 为`Bug`修复使用专门分支，让团队可以处理掉问题而不用打断其它工作或是等待下一个发布循环。
你可以把维护分支想成是一个直接在`master`分支上处理的临时发布。

是吧？

关于方便说明`hotfix`，先说一下如何约定发布的版本号，比如成熟完整的是[语义化版本](http://semver.org/lang/zh-CN/)，简单地说，使用三位版本号，分别如下：

- 主版本（一位版本），表示有不兼容的大升级，不仅仅是新加和修改功能。如`2.0.0`
- 次版本号（二位版本），表示新加了功能。如`1.1.0`
- 修订号（三位版本），修正问题，没有新加功能。`hotfix`是指紧急不能等的问题。体现在这个版本号中。如`1.1.1`。

**Comment by ThomasLau** [comment]
是的，是 [Gitflow工作流 - 维护分支](https://github.com/oldratlee/translations/blob/master/git-workflows-and-tutorials/workflow-gitflow.md#%E7%BB%B4%E6%8A%A4%E5%88%86%E6%94%AF)这里，抱歉，应该放个链接:smiley:
其实，Vincent Driessen模型很清晰，我之前觉得  <i>不符合规范</i>  是因为觉得发布流程应该仅在一个分支上面做(实际上，一些公司规定只能在Release上面做发布)，所以hotfix虽然fork master，但却是作为一个特别的release来用，不过，这样hotfix和release就分的不清晰了。
ps，上面讲版本号也很实用:smiley:

**Comment by oldratlee** [comment]
> 不符合规范 是因为觉得发布流程应该仅在一个分支上面做(实际上，一些公司规定只能在`Release`上面做发布)

嗯，“发布流程应该仅在一个分支上面做”，这个也可以。
＃ 你说的“一个分支”其实只要使用一个分支名就可以了（方便发布系统使用，因为它可能只认一个固定的名字）。

**Comment by ThomasLau** [comment]
:smile: ,有类似的地方,不过push -f 不敢用的，除非是rebase的时候图方便的。

谢谢啦！

**Comment by oldratlee** [comment]
不客气～ :smile:
