### ISSUE TITLE
刚开始学习Git及Github

### ISSUE THREAD

**Issue by newjie** [oldratlee/translations#22]
希望楼主能整理一下`Git`及`Github`术语的中英文对照表，比如

- `Repository`是否对应仓库
- `Pull Request`是否对应提交？

**Comment by oldratlee** [comment]
不错的想法的， :+1: 

你看这个资料[`Git`的资料整理](https://github.com/xirong/my-git) by [@xirong](https://github.com/xirong)，看看能不能在学习的过程中你来整理一份。

PS：

个人对『中英文对照表』的想法是

- 首先记得并使用英文术语
- 只在直白没有混淆的情况会用中文

所以 一直没有在意去整理 『中英文对照表』 :smile:
