### ISSUE TITLE
你好，想问下关于git flow的develop分支上的合并操作？

### ISSUE THREAD

**Issue by Howld** [oldratlee/translations#23]
[workflow-gitflow.md#小红完成发布
](https://github.com/oldratlee/translations/blob/master/git-workflows-and-tutorials/workflow-gitflow.md#%E5%B0%8F%E7%BA%A2%E5%AE%8C%E6%88%90%E5%8F%91%E5%B8%83)
  
在小红完成功能开发中，本地some-feature分支先是合并了远程develop分支，然后本地develop分支合并了本地some-feature分支之后提交，然后删除了本地some-feature分支。

1. 远程是否存在some-feature分支？
2. 那么在小红完成发布中，本地release-0.1分支是否应该在本地master分支合并完成之后，先合并来自远程develop分支的代码，然后本地develop分支合并本地release-0.1分支，然后提交？

**Comment by oldratlee** [comment]
> 1.远程是否存在some-feature分支？

开发过程中，可以把本地 feature分支 push到远程，远程是用于备份。

> 2.那么在小红完成发布中，本地release-0.1分支是否应该在本地master分支合并完成之后，先合并来自远程develop分支的代码，然后本地develop分支合并本地release-0.1分支，然后提交？

完整类型的分支体现在：

![](https://github.com/oldratlee/translations/blob/master/git-workflows-and-tutorials/images/git-workflow-release-cycle-4maintenance.png)

上面的图主要 看的是 修改内容 在分支之间的流向(流向就是合并来完成)，梳理就是：

- master  => hotfix => develop/master
- develop => feature => develop => release => develop/master

总结一下，目标都是 develop/master，区别是 develop分支是面向开发收集，而master面向发布的收集。

你提到的分支类型是  release(release-0.1)、master、develop，梳理就是（上面完整梳理的一部分）：

release => develop/master

这个过程理解 可以先不管，远程 还是 本地。

要注意的是，在合并时，本地分支要和远程分支是一致的，即可（避免合并时丢了提交）。

**Comment by Howld** [comment]
我的意思是develop分支在开出release之后，有提交更新，那之后release分支要合并回来，是否应该先从develop分支合并新的提交？还是直接就合并回develop分支（感觉对合并不同分支，不是很理解）？

**Comment by oldratlee** [comment]
> 之后release分支要合并回develop，是否应该先从develop分支合并新的提交？还是直接就合并回develop分支（感觉对合并不同分支，不是很理解）？

对于develop分支，上面2种方式是一样的。

release（比如release-0.1）分支合并到master，打了tag后就可以删除，没有必要去合并develop分支。
