### ISSUE TITLE
wiki的用法简介

### ISSUE THREAD

**Issue by lupupu** [oldratlee/translations#35]
可否把github上的wiki的用法简介给写一下呢？或者推荐一个相关文档也可以。多谢啦！ @oldratlee

**Comment by oldratlee** [comment]
github上的wiki我不怎么用

一方面是我倾向于直接在代码工程中写markdown文档（一般的项目往往文档很少就几页）；另一方面是 语法与GFM不一致。

wiki具体可以找和看一下github的官方使用文档。
