### ISSUE TITLE
『API设计原则』翻译建设：could have翻译不要丢掉虚拟语气

### ISSUE THREAD

**Issue by sishier** [oldratlee/translations#37]
> For example, QMimeSourceFactory in Qt 3 could have been called QImageLoader and have a different API.  举个例子，在Qt 3中，QMimeSourceFactory不应命名成QImageLoader并有不一样的API。

could have 虚拟语气。 如果不是为了简介清晰，QMimeSourceFactory 在Qt 3中会被叫做QImageLoader并有一套不同的API.

**Comment by oldratlee** [comment]
👍 

方便给个pull request，提交修改吗？

**Comment by oldratlee** [comment]
@sishier 已经修正， 谢谢建议  :)
