### ISSUE TITLE
clean extra TTL value in destination thread

### ISSUE THREAD

**Issue by tianjialin** [oldratlee/translations#51]
您好，请教一个问题：

在`TransmittableThreadLocal`类中的 `backupAndSet()`  方法中，如下代码：

```java
for (Iterator<? extends Map.Entry<TransmittableThreadLocal<?>, ?>> iterator = holder.get().entrySet().iterator();
             iterator.hasNext(); ) {
    Map.Entry<TransmittableThreadLocal<?>, ?> next = iterator.next();
    TransmittableThreadLocal<?> threadLocal = next.getKey();

    // 此处将线程池所在线程threadlocal备份
    backup.put(threadLocal, threadLocal.get());

    // 没太理解此处，为何将copied中不存在，holder中存在的 threadlocal remove？
    if (!copied.containsKey(threadLocal)) {
        iterator.remove();
        threadLocal.superRemove();
    }
}
```

#### 一旦调用`iterator.remove()`本来不属于当前线程的`threadlocal`也会被`remove`，这样假如此时另外一个线程池中的线程调用了`copy()`方法，就会丢失部分数据？

不知我哪里理解错误，望批评指正。
期待回复

**Comment by oldratlee** [comment]
> 这样假如此时  **_另外一个线程池中的线程_** 调用了copy()方法

`holder.get()`是`ThreadLocal`的，只属于当前线程。

即这个数据不会被另一个线程访问使用的，没有并发问题。

更具体 可以再看看一下`ThreadLocal`。

@tianjialin 
这个Issue也提交错了 仓库，请 提交到 https://github.com/alibaba/transmittable-thread-local

**Comment by tianjialin** [comment]
仔细有想了想 ThreadLocal 的运行原理，理解了，非常感谢百忙之中回复。

另：
我是单击 TransmittableThreadLocal 仓库下README里 “建议和提问，提交Issue” 进来的，我还以为提问都是在这提问。操作有误，实在抱歉
