### ISSUE TITLE
Gitflow工作流第1个图存在错误？

### ISSUE THREAD

**Issue by iqianxing** [oldratlee/translations#53]
1、Gitflow工作流第1个图存在错误
![image](https://user-images.githubusercontent.com/2938263/42427463-2b8b91a2-8361-11e8-8d42-c97beb854b52.png)

2、参考数据来自作者提供的链接[nvie的流程图](https://nvie.com/posts/a-successful-git-branching-model/)
![image](https://user-images.githubusercontent.com/2938263/42427523-8407d2b4-8361-11e8-9ba7-d1f2d364b843.png)

**Comment by oldratlee** [comment]
我也看看

**Comment by oldratlee** [comment]
是的，这个箭头的方向 应该是 画反了。

ps： 译文的图来自 英文原来，没有修改过。

**Comment by oldratlee** [comment]
@iqianxing  上面的提交已经Fix

**Comment by iqianxing** [comment]
Thank you.
