### ISSUE TITLE
overlapping-experiment-infrastructure-more-better-faster-experimentation 一处错误

### ISSUE THREAD

**Issue by lemon-simple** [oldratlee/translations#69]
原文：
“如果请求在重叠域，那么请求最多在一个实验中（这个实验可以改变参数集合中的任意参数的值），如果请求在重叠域，那么请求最多在三个实验中，每层一个实验。并且对于每个实验，只能使用对应层的参数。”

第一句话应该是：如果请求在非重叠域

**Comment by oldratlee** [comment]
@lemon-simple 谢谢指出。

已修正并提交。
