### ISSUE TITLE
Fork/Join Typo

### ISSUE THREAD

**Issue by jy03078584** [oldratlee/translations#80]
Hi 关于[`Fork/Join`章节摘要部分](https://github.com/oldratlee/translations/blob/master/a-java-fork-join-framework/README.md#0-%E6%91%98%E8%A6%81)
- Paper原文：
>This paper describes the design, implementation, and
performance of a Java framework for supporting a style of
parallel programming in which problems are solved by
(recursively) splitting them into subtasks that are solved in
parallel, waiting for them to complete, and then composing
results. The general design is a variant of the work−stealing
framework devised for Cilk. The main implementation
techniques surround efficient construction and management of
tasks queues and worker threads. The measured performance
shows good parallel speedups for most programs, but also
suggests possible improvements.

- 原译文
>本论文描述了一个Java框架的设计、实现以及性能，这个框架了一种并行编程风格（a style of parallel programming）：解决问题的方式是通过把问题（递归地）分拆为子任务，并行地解决这些子任务，等这些子任务完成，然后合并子任务的结果

---
- 调整为以下如何

本论文描述了一种支持并行编程风格（a style of parallel programming）的Java框架的设计、实现以及性能。它解决问题的方式是通过把问题（递归地）分拆为子任务，并行地解决这些子任务，等这些子任务完成，然后合并子任务的结果

**Comment by oldratlee** [comment]
收到 ❤️

**Comment by oldratlee** [comment]
commit the modification in PR #81 by @jy03078584  ♥️
